<?php
/** @var $block \Kapana\MySignup\Block\Signup */
if (!$block->isSignupEnabled()) {
    // Optionally display a message or simply output nothing.
    echo __('The sign-up form is disabled.');
    return; // Prevents the rest of the template from rendering.
}
?>
<h1>Sign Up</h1>
<form action="<?= $block->getUrl('mysignup/index/post') ?>" method="POST">
    <input type="hidden" name="form_key" value="<?= $block->getFormKey(); ?>"/>

    <div>
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required/>
    </div>

    <div>
        <label for="date">Date:</label>
        <input type="date" id="date" name="date" required/>
    </div>

    <div>
        <button type="submit">Submit</button>
    </div>
</form>
