<?php
/** @var $block \Magento\Framework\View\Element\Template */
$enabled = $block->getScopeConfig()->getValue('signup_config/general/enabled', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);

if (!$enabled) : ?>
    <div class="message error">Form not enabled</div>
<?php else: ?>
    <form action="<?= $block->getUrl('signup/index/post') ?>" method="POST">
        <label for="name">Name</label>
        <input type="text" name="name" required/>

        <label for="date">Date</label>
        <input type="date" name="date" required/>

        <button type="submit">Submit</button>
    </form>
<?php endif; ?>
